In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [25]:
def train_perceptron_2(X, y, learning_rate):
    # w = np.random.random(3)
    w = np.array([5, 1, 1])

    for i in range(50):
        num_iter = i + 1

        yXw = (y * X) @ w.T
        mistake_ids = np.where(yXw <= 0)[0]
        if mistake_ids.size > 0:
            i = np.random.choice(mistake_ids)
            w = w + learning_rate * y[i] * X[i]
            print(w, num_iter)
        else:
            return w, num_iter
    return w, num_iter

In [58]:
X = np.array([[-2, -1],
              [2, -1],
              [1, 1],
              [-1, -1],
              [3, 2]])
X = np.concatenate((np.ones([len(X), 1]), X), axis=1)
y = np.array([-1, 1, 1, -1, 1]).reshape(5, -1)

In [37]:
train_perceptron(X, y, 0.4)

[4.6 1.4 1.4] 1
[4.2 1.8 1.8] 2
[3.8 2.2 2.2] 3


(array([3.8, 2.2, 2.2]), 4)

In [98]:
def train_perceptron(X, y, learning_rate):
    # w = np.random.random(3)
    w = np.array([5, 1, 1])

    coveraged = False
    num_iter = 0
    while not coveraged:
        coveraged = True

        for X_i, y_i in zip(X, y):
            num_iter += 1
            print("Iteration " + str(num_iter) + ": ", round(w.T @ X_i, 2), round(y_i * w.T @ X_i, 2))
            if y_i * X_i @ w.T <= 0:
                w = w + learning_rate * y_i * X_i
                coveraged = False
            print(w)

    return w

In [105]:
X = np.array([[-2, -1],
              [2, -1],
              [1, 1],
              [-1, -1],
              [3, 2]])
X = np.concatenate((np.ones([len(X), 1]), X), axis=1)
y = np.array([-1, 1, 1, -1, 1]).reshape(5, -1)

w = train_perceptron(X, y, 0.4)
print()


# Question b

def sgn(x):
    return 1 if x>0 else -1

x = np.array([1, -5, 3])
wTx = round((w.T @ x), 2)
print("Predicted value = " + str(wTx))
print("Predicted class = " + str(sgn(wTx)))

Iteration 1:  2.0 -2.0
[4.6 1.8 1.4]
Iteration 2:  6.8 6.8
[4.6 1.8 1.4]
Iteration 3:  7.8 7.8
[4.6 1.8 1.4]
Iteration 4:  1.4 -1.4
[4.2 2.2 1.8]
Iteration 5:  14.4 14.4
[4.2 2.2 1.8]
Iteration 6:  -2.0 2.0
[4.2 2.2 1.8]
Iteration 7:  6.8 6.8
[4.2 2.2 1.8]
Iteration 8:  8.2 8.2
[4.2 2.2 1.8]
Iteration 9:  0.2 -0.2
[3.8 2.6 2.2]
Iteration 10:  16.0 16.0
[3.8 2.6 2.2]
Iteration 11:  -3.6 3.6
[3.8 2.6 2.2]
Iteration 12:  6.8 6.8
[3.8 2.6 2.2]
Iteration 13:  8.6 8.6
[3.8 2.6 2.2]
Iteration 14:  -1.0 1.0
[3.8 2.6 2.2]
Iteration 15:  16.0 16.0
[3.8 2.6 2.2]

Predicted value = -2.6
Predicted class = -1


In [71]:
def train_perceptron_2(X, y, learning_rate):
    # w = np.random.random(3)
    w = np.array([5, 1, 1])

    for i in range(50):
        num_iter = i + 1

        yXw = (y * X) @ w.T
        mistake_ids = np.where(yXw <= 0)[0]
        if mistake_ids.size > 0:
            i = np.random.choice(mistake_ids)
            w = w + learning_rate * y[i] * X[i]
            print(w, num_iter)
        else:
            return w, num_iter
    return w, num_iter

In [73]:
train_perceptron_2(X, y, 0.4)

[4.6 1.8 1.4] 1
[4.2 2.2 1.8] 2
[3.8 2.6 2.2] 3


(array([3.8, 2.6, 2.2]), 4)

In [111]:
# Question c

x_new = np.array([1, 2, 2])
y_new = -1
X = np.vstack([X, x_new])
y = np.vstack([y, y_new])

In [117]:
np.concatenate((X, y), axis=1)

array([[ 1., -2., -1., -1.],
       [ 1.,  2., -1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1., -1., -1., -1.],
       [ 1.,  3.,  2.,  1.],
       [ 1.,  2.,  2., -1.]])

In [118]:
train_perceptron(X, y, 0.4)

# not coverage

Iteration 1:  2.0 -2.0
[4.6 1.8 1.4]
Iteration 2:  6.8 6.8
[4.6 1.8 1.4]
Iteration 3:  7.8 7.8
[4.6 1.8 1.4]
Iteration 4:  1.4 -1.4
[4.2 2.2 1.8]
Iteration 5:  14.4 14.4
[4.2 2.2 1.8]
Iteration 6:  12.2 -12.2
[3.8 1.4 1. ]
Iteration 7:  -0.0 0.0
[3.8 1.4 1. ]
Iteration 8:  5.6 5.6
[3.8 1.4 1. ]
Iteration 9:  6.2 6.2
[3.8 1.4 1. ]
Iteration 10:  1.4 -1.4
[3.4 1.8 1.4]
Iteration 11:  11.6 11.6
[3.4 1.8 1.4]
Iteration 12:  9.8 -9.8
[3.  1.  0.6]
Iteration 13:  0.4 -0.4
[2.6 1.8 1. ]
Iteration 14:  5.2 5.2
[2.6 1.8 1. ]
Iteration 15:  5.4 5.4
[2.6 1.8 1. ]
Iteration 16:  -0.2 0.2
[2.6 1.8 1. ]
Iteration 17:  10.0 10.0
[2.6 1.8 1. ]
Iteration 18:  8.2 -8.2
[2.2 1.  0.2]
Iteration 19:  -0.0 0.0
[2.2 1.  0.2]
Iteration 20:  4.0 4.0
[2.2 1.  0.2]
Iteration 21:  3.4 3.4
[2.2 1.  0.2]
Iteration 22:  1.0 -1.0
[1.8 1.4 0.6]
Iteration 23:  7.2 7.2
[1.8 1.4 0.6]
Iteration 24:  5.8 -5.8
[ 1.4  0.6 -0.2]
Iteration 25:  0.4 -0.4
[1.  1.4 0.2]
Iteration 26:  3.6 3.6
[1.  1.4 0.2]
Iteration 27:  2.6 2.6


KeyboardInterrupt: 